### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by mingan** [vivkr/haml_tailwind_monkeypatch#1]
Hi, I really love this monkey patch and would love to use it because

```haml
%h1.font-bold.text-2xl.lg:text-4xl.text-grey-600.mt-2.lg:mt-6.leading-tight.group-hover:text-black.group-focus:text-black.transition.duration-150.ease-in-out
```

doesn't look great.

Do you mind adding a licence to the repo so we can see whether we can use it?

**Comment by v-raja** [comment]
Yup, please feel free to use it. Will add a MIT license when I'm on the computer.

**Comment by v-raja** [comment]
Done. Let me know if you have any problems with the MIT license.
